name: Code Review Workflow

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Add steps for installing dependencies if necessary

    - name: Get List of Changed Files
      uses: jitterbit/get-changed-files@v1
      with:
       format: 'space-delimited'
 


    - name: Prepare and Send Each File to API
      id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for file in ${{ steps.files.outputs.all }}
        do
          echo "Processing file: $file"
          json_payload=$(python scripts/create_payload.py "$file")
          echo "Payload is created"
          response=$(curl --location --request POST '${{ secrets.TUNNEL_URL }}' \
                    --header 'Content-Type: application/json' \
                    --data "$json_payload")
          echo "API Response for $file: $response"
          geqi=$(echo $response | jq .geqi)
          recommendations=$(echo $response | jq .recommendations)

          if [[ $geqi -lt 70 ]]; then
            echo "GEQI Score for $file is below the acceptable threshold."
            exit 1
          fi
        done    